### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hubshi** [yoppy-tjhin/meshTopologyVisualizer#4]
Thank you for sharing this good tool, I reached here from your YouTube video. I have tried to run you code but I am getting the following error:

`python main_window.py 

qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "main_window.py", line 15, in <module>
    window = MyApp()
  File "main_window.py", line 10, in __init__
    self.setupUi(self)
  File "/home/pi/D/top.py", line 30, in setupUi
    self.figure, self.node_collection = self.setupPlot()  # yoppy
  File "/home/pi/D/top.py", line 124, in setupPlot
    cf, node_collection = nx.draw(self.G)
TypeError: 'NoneType' object is not iterable
`
Kindly guide me to fix this error.

Best regards!

**Comment by rmccown** [comment]
I'm getting a similar error

Traceback (most recent call last):
  File "main_window.py", line 15, in <module>
    window = MyApp()
  File "main_window.py", line 10, in __init__
    self.setupUi(self)
  File "/Users/bob/Projects/meshTopologyVisualizer/top.py", line 30, in setupUi
    self.figure, self.node_collection = self.setupPlot()  # yoppy
  File "/Users/bob/Projects/meshTopologyVisualizer/top.py", line 124, in setupPlot
    cf, node_collection = nx.draw(self.G)
TypeError: cannot unpack non-iterable NoneType object

**Comment by rmccown** [comment]
Im getting the same error.  Reading the comments in the code, it looks like there might be a file missing?  The modified mx_pylab.py?

> 
>        # draw() is in nx_pylab.py
>       # By default draw() returns nothing. draw() is modified to return cf & node_collection
>        # Because we need cf (plot figure reference) here to embed it on our top app window
>        # node_collection is used when we need to detect whether a node is clicked
>        cf, node_collection = nx.draw(self.G)

**Comment by jorgelvv** [comment]
Yes, according to the comment if you use a higher version than 2.0 of the nerworkx library you have to make the modification. The address is something like this:
C:\Users\USER_NAME\AppData\Local\Programs\Python\Python39\Lib\site-packages\networkx\drawing.

It will also give you an error "ImportError: cannot import name 'gcd' from 'fractions' (C:\Users\USER_NAME\AppData\Local\Programs\Python\Python39\lib\fractions.py)", since for python 3.9 gcd is now in the math library, just change the "from fractions import gcd" to "from math import gcd" in the dag.py file at the following address: "C:\Users\USER_NAME\AppData\Local \Programs\Python\Python39\Lib\site-packages\networkx\algorithms"

But I still have problems, now the warning that appears is the following: NameError: name 'node_collection' is not defined.
Could someone solve it?
